variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "af-south-1"
}

variable "app_name" {
  description = "Application name used for resource naming"
  type        = string
  default     = "xmltojson-judgment-transformation"
}

variable "instance_type" {
  description = "EC2 instance type (t3.micro is free-tier eligible)"
  type        = string
  default     = "t3.micro"
}

variable "registry_table_name" {
  description = "DynamoDB table for the processing-record registry"
  type        = string
  default     = "xmltojson-processing-records"
}

variable "api_key" {
  description = "Deprecated - the API key is generated by Terraform and stored in SSM. Kept for override; empty means use the generated one."
  type        = string
  default     = ""
  sensitive   = true
}

variable "domain_name" {
  description = "Domain (A record) pointing at the Elastic IP; Caddy obtains a Let's Encrypt cert for it"
  type        = string
  default     = "xmltojsonappbythatomakola.gbrbo.co.za"
}

variable "image_tag" {
  description = "Docker image tag to run"
  type        = string
  default     = "latest"
}
